
tag_dict = {\
    1: u'Briana Burton',
	2: u'Nature Neuroscience',
	3: u'publication',
	4: u'awards',
	5: u'Hoopes Prize',
	6: u'Lawrence J. Henderson Prize',
	7: u'Florian Engert',
	8: u'Susan Mango',
	9: u' MCB Outreach Program',
	10: u'Bloch Lecture',
	11: u'John T. Edsall Lecture',
	12: u'Nature',
	13: u'Holiday Gift Drive',
	14: u'Science',
	15: u'Proceedings of the National Academy of Sciences',
	16: u'Catherine Dulac',
	17: u'Fellow in the American Association for the Advancement of Science',
	18: u'Excellence in Mentoring Award from the American Association of Immunologists',
	19: u'Microbial Sciences Symposium',
	20: u'Microbial Sciences Initiative at Harvard',
	21: u'Neuron',
	22: u'Molecular Cell',
	23: u'Vlad Denic',
	24: u'profile',
	25: u'Craig Hunter',
	26: u'PLoS Biology',
	27: u'charitable work',
	28: u'2010',
	29: u'2009',
	30: u'2008',
	31: u'2007',
	32: u'2006',
	33: u'2005',
	34: u'2004',
	35: u'2003',
	36: u'Journal of Biological Chemistry',
	37: u'David Jeruzalmi',
	38: u'Gregory Verdine',
	39: u'Richard Losick',
	40: u'Sloan Foundation Fellowship',
	42: u'Nature Cell Biology',
	43: u'Canada Gairdner Award',
	44: u'Engineering and Physical Biology Symposium',
	45: u'Prather Lectures',
	46: u'James C. Wang',
	47: u'book',
	48: u'Graduate Student Fellowships',
	49: u'Gilliam Fellowship from the Howard Hughes Medical Institute',
	50: u'National Science Foundation Graduate Research Fellowship',
	51: u'Matthew Meselson',
	52: u'Andrew McMahon ',
	53: u'Genes and Development ',
	54: u'Nature Structural & Molecular Biology',
	55: u'Nature Genetics',
	56: u'Markus Meister',
	57: u"Erin O'Shea",
	58: u'Boston Bacterial Meeting',
	59: u'Venkatesh Murthy',
	60: u'Jeff Lichtman',
	61: u'Nancy Kleckner',
	62: u'Cell',
	63: u'Cell Stem Cell',
	64: u'Takao Hensch',
	65: u'Nicole Francis',
	66: u'New Scholar Awardee in Aging',
	67: u'Journal of Neuroscience',
	68: u'Alexander Schier',
	69: u'Royal Society of London',
	71: u'Ernest Peralta Fund Award',
	72: u'William Gelbart',
	73: u'Joshua Sanes',
	74: u'Olympus BioScapes Digital Imaging Competition',
	75: u'Andres Leschziner',
	76: u'Merck Genome-Related Research Awards',
	77: u'rhinos',
	78: u'Woody Hastings',
	79: u'CSHL Genome Research Poster Competition',
	80: u'Vicki Sato',
	81: u'Douglas Melton',
	82: u'Kevin Eggan',
	83: u'Howard Berg',
	84: u'U.S. Genomics Award for Outstanding Investigator',
	85: u'honorary degree',
	86: u'Rachelle Gaudet',
	87: u'Klingenstein Fellowship Award',
	88: u'Tom Maniatis',
	89: u"Victoria D'Souza",
	90: u'Naoshige Uchida',
	91: u'Axel Nohturfft',
	92: u'Lounsbery Award',
	93: u'Selman A. Waksman Award in Microbiology',
	94: u'Biophysical Journal',
	95: u'symposium',
	96: u'Genetics and Genomics Training Program',
	97: u"Harvard's Mind/Brain/Behavior Initiative (MBB)",
	98: u'Sam Kunes',
	99: u'Developmental Cell',
	100: u'Howard Hughes Medical Institute (HHMI)',
	101: u'McKnight Scholar Award',
	102: u'Cold Spring Harbor Laboratory',
	103: u'Jack Strominger',
	104: u'The Journal of Cell Biology',
	105: u'Peter C. Farrell Prize in Sleep Medicine',
	106: u'Andrew Murray',
	107: u'Development',
	108: u'MacArthur Fellow',
	109: u'Raymond Erikson',
	110: u'Molecular and Cellular Biology',
	111: u'Matthew Michael',
	112: u'Robert Lue',
	113: u'Merck-Wiley Fellowship',
	114: u'Golden Brain Award',
	115: u'Howard Temin Award',
	116: u'American Philosophical Society ',
	117: u'Nature Immunology',
	118: u'Stowers Medical Institute',
	119: u'FlyBase',
	120: u'Javits Award',
	121: u'Benjamin de Bivort',
	122: u'John Dowling',
	123: u'undergraduate education',
	124: u'ASBMB-Merck Award',
	125: u'Center for Brain Science',
	126: u'Lasker Award',
	127: u'MCB Research Retreat',
	128: u'MCB Chair',
	129: u'Lawrence Bogorad',
	130: u'Professor Emeritus',
	131: u'New England Journal of Medicine',
	132: u'Jeffries Wyman Fellowship',
	133: u'Stem Cell Institute',
	134: u'motion studies',
	135: u'American Academy of Arts and Sciences',
	136: u'Life Sciences Council',
	137: u'Don Wiley',
	138: u'Milstein Award',
	139: u'Harvard-Bangalore Science Initiative',
	140: u'Meselson Prize',
	141: u'Sharad Ramanathan',
	142: u'Nature Medicine',
	143: u'lecture',
	144: u'James Watson',
	145: u'Karine Gibbs',
	146: u'Paul Doty Lecture',
	147: u'George W. Beadle Award',
	148: u'Philippe Cluzel',
	149: u'2012',
	150: u'2011',
	151: u"Hutchinson Cancer Research Center's Harold M. Weintraub Graduate Student Award",
	152: u'Harvard Heroes',
	153: u'National Defense Science and Engineering Graduate Fellowship',
	154: u'Hertz Foundation Graduate Fellowship',
	155: u'fellowship',
	156: u'Current Biology',
	157: u'Conte Center at Harvard',
	158: u'Food Drive',
	159: u'Hopi Hoekstra',
	160: u'NIH Directors Pioneer Award',
	161: u'Pew Scholar in Biomedical Sciences',
	162: u'Milton E. Cassel Scholar',
	163: u'Perl/UNC Neuroscience Prize',
	164: u'video',
	165: u'Guo-Liang Chew',
	166: u'Ghazal Ashrafi',
	167: u'Zambo',
	168: u'Dog',
	169: u'course',
	170: u'class',
	171: u'MCB 157',
	172: u'MCB 121',
	173: u'Ethan Garner',
	174: u'MCB faculty',
	175: u'Hannah Shen',
	176: u'Askin Kocabas',
	177: u'Horwitz Prize',
	178: u'HARVARDgazette',
	179: u'PNAS',
	180: u'Estela Medrano Award',
	181: u'award',
	182: u'Packard Foundation Fellowship',
	183: u'Koshland',
	184: u'Peralta Prize',
	185: u'Harvey Lecture',
	186: u'David Cox',
	187: u'Assistant Professor',
	188: u'edX',
	189: u'Life Sciences',
	190: u'Professor',
	191: u'eLife',
	192: u'MCB 144',
	193: u'David A. Haig',
	194: u'MCB 162',
	195: u'2013',
	196: u'MCO Outreach Program',
	197: u'Summer Program',
	198: u'SROH',
	199: u'Undergraduate Summer Internship',
	200: u'Smith Family Foundation',
	201: u'High School Outreach',
	202: u'Fannie Cox Prize for Excellence in Science Teaching',
	203: u'Derek Bok Center for Teaching and Learning',
	204: u'MSI',
	205: u'Searle Scholar',
	206: u'MCB Graduate Student',
	207: u'MCB Graduate Student Kenneth Skinner Awarded 3 Fellowships (GEM)',
	208: u'NSF Graduate Research Fellowship',
	209: u'Ford Foundation Predoctoral Fellowship',
	210: u'Thomas Temple Hoopes Prize',
	211: u'John E. Dowling Thesis Prize',
	212: u'Bowdoin Prize in the Natural Sciences',
	213: u'Undergraduate Prizes',
	214: u'Nature Methods',
	215: u'BBM',
	216: u'epb',
	217: u'Engineering and Physical Biology (EPB)',
	218: u'McGill University',
	219: u'Cell Reports',
	220: u'Tenure',
	221: u'Promotion',
	222: u'Post Doctorates Fellowships',
	223: u'2014',
	224: u'HHMI International Research Fellowship',
	225: u'Fall semester',
	226: u'Online Education',
	227: u'Scientific American',
	228: u'New York Times',
	229: u'In the News',
	230: u'graduate student award',
	231: u'MCB award',
	232: u'preceptor',
	233: u'MCB in the NEWS',
	234: u'Genetics',
	235: u'MCB 68',
	236: u'teaching',
	237: u'Laura Magnotti',
	238: u'National Geographic',
	239: u'special seminar',
	240: u'nature communications',
	241: u'MCB concentration',
	242: u'education',
	243: u'graduate student education',
	244: u'Postdoctoral Research Fellow',
	245: u'Everett Mendelsohn Excellence in Mentoring Award',
	246: u'Tom Torello',
	247: u'MCB 60',
	248: u'National Academy of Sciences',
	249: u'new course',
	250: u'MCB 101',
	251: u'Postdoctoral Fellowships',
	252: u'College Professorship',
	253: u'HHMI Professor',
	254: u'postdoctoral award',
	255: u'postdoc profile',
	256: u'faculty profile',
	257: u'Google Faculty Research Award',
	258: u'MCB 63',
	259: u'MCB course',
	260: u'Bjorkman-Strominger-Wiley Prize',
	261: u'Doty-Losick Prize for Exceptional Service',
	262: u'Meselson Prize for the Most Beautiful Experiment',
	263: u'Raymond and Beverly Sackler International Prize in Biophysics',
	264: u'Brain Research through Advancing Innovative Neurotechnologies',
	265: u'Haim Sompolinsky',
	266: u'NIH New Innovator Award (DP2)',
	267: u'Summer Research Opportunities at Harvard',
	268: u'mco',
	269: u'2014 Double Helix Medal',
	270: u'Daniel Kahne',
	271: u'Rhodes Scholar',
	272: u'Phi Beta Kappa',
	273: u'PBK',
	274: u'honors',
	275: u'Phi Beta Kappa (PBK)',
	276: u'undergraduate',
	277: u'2015',
	278: u'Sean Eddy',
	279: u'Elena Rivas',
	280: u'Pradel Research Award',
	281: u'Richard Lounsbery Award',
	282: u'Technology',
	283: u'Harvard EdPortal',
	284: u'HarvardX',
	285: u'community outreach',
	286: u'Engineering and Physical Biology (EPB) Symposium',
	287: u'Derek C. Bok Award',
	288: u'Nature Biotechnology',
	289: u'glamour magazine',
	290: u'Alain Viel',
	291: u'Harvard Magazine',
	292: u'neuroscience contentration',
	293: u'Charlie Rose',
	294: u'EPB Symposium Review',
	295: u'Developmental Biology',
	296: u'Smithsonian Magazine',
	297: u'THURJ',
	298: u'The Harvard Undergraduate Research Journal',
	299: u'Harvard Center for Biological Imaging',
	300: u'HCBI',
	301: u'HHMI Gilliam Fellowship',
	302: u'Early Career Life Scientist Award',
	303: u'The American Society for Cell Biology',
	304: u'science feature',
	305: u'summer program in Japan',
	306: u'summer program in India',
	307: u'summer program in Paris, France',
	308: u'Structure',
	309: u'obituary',
	310: u'Norbert Perrimon',
	311: u'Cell Systems',
	312: u'2015 MBB Distinguished Harvard Lecture',
	313: u'undergraduate initiative',
	314: u'undergraduate scholarship',
	315: u'Marshall Scholarship',
	316: u'Harvard Crimson ',
	317: u'2016',
	318: u'FAS Facility',
	319: u'Intelligence Advanced Research Projects Activity (IARPA) Grant',
	320: u'Thomas Hunt Morgan Medal ',
	321: u'Larry Katz Memorial Prize Lecture',
	322: u'neuroscience concentration',
	323: u'Cassandra Extavour',
	324: u'graduate program',
	325: u'graduate student initiatives',
	326: u'graduate students',
	327: u'Mott Hall Bridges Academy',
	328: u'MHBA',
	329: u'teaching award',
	330: u'MCB lecturer',
	331: u'National Academy of Sciences (NAS)',
	332: u'graduate student outreach',
	333: u'GSAS Commencement Speech',
	334: u'MCO Honors',
	335: u'Harvard Hero award',
	336: u'Doug Richardson',
	337: u'History of Neurobiology in the FAS',
	338: u'MCB history',
	339: u'MCO Initiatives',
	340: u'Historical Perspecitve',
	341: u'Daniel Branton',
	342: u'staff profile',
	343: u'reseasrch',
	344: u'research',
	345: u'Physical and Chemical Biology (PCB) Concentration',
	346: u'hhmi faculty scholar',
	347: u'faculty position',
	348: u'Doeke Hekstra',
	349: u'nanocourse',
	350: u'Ruth Hubbard',
	351: u'In Memoriam',
	352: u'Daniel J. Needleman'}
